version: '3.5'
services:
  db:
    image: mysql:8
    container_name: nestjs-mikro-orm-test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: super-secret
      MYSQL_DATABASE: shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: secret
    ports:
      - '33071:3306'
    networks: [nestjs-mikro-orm-test]

networks:
  nestjs-mikro-orm-test:
    driver: bridge
    name: nestjs-mikro-orm-test
